# Generated by Django 4.0.3 on 2022-04-01 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MatchStatusses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('biography', models.CharField(max_length=1000)),
                ('profile_picture', models.FileField(upload_to='')),
                ('phone_number', models.CharField(max_length=20)),
                ('private', models.BooleanField()),
                ('online', models.BooleanField()),
                ('physical', models.BooleanField()),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bijles_backend.locations')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('active', models.BooleanField()),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bijles_backend.profiles')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bijles_backend.roles')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bijles_backend.subjects')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bijles_backend.users')),
            ],
        ),
        migrations.CreateModel(
            name='RolesPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bijles_backend.permissions')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bijles_backend.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('rating', models.IntegerField(default=1)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallo', to='bijles_backend.users')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jemama', to='bijles_backend.users')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bijles_backend.users')),
                ('subject_id', models.ForeignKey(on_delete=models.SET('Onbekend'), to='bijles_backend.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bijles_backend.matchstatusses')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='bijles_backend.users')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='bijles_backend.users')),
            ],
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='')),
                ('caption', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bijles_backend.users')),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.CharField(max_length=500)),
                ('price', models.FloatField(blank=True, default=None, null=True)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bijles_backend.requests')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bijles_backend.users')),
            ],
        ),
    ]
