# Generated by Django 4.0.3 on 2022-04-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bijles_backend', '0002_alter_profiles_biography_alter_profiles_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='physical',
            field=models.BooleanField(default=None),
        ),
    ]
