# Generated by Django 4.0.3 on 2022-04-03 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bijles_backend', '0006_languages_levels_profiles_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='language',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bijles_backend.languages'),
        ),
        migrations.AddField(
            model_name='requests',
            name='level',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bijles_backend.levels'),
        ),
    ]
