# Generated by Django 4.0.3 on 2022-04-03 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bijles_backend', '0008_availability_useravailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bijles_backend.languages'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bijles_backend.levels'),
        ),
    ]
