# Generated by Django 4.0.3 on 2022-04-03 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bijles_backend', '0009_alter_requests_language_alter_requests_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='student',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='teacher',
        ),
        migrations.AddField(
            model_name='matches',
            name='initiator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='initiator', to='bijles_backend.users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matches',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='bijles_backend.users'),
            preserve_default=False,
        ),
    ]
